### [numpy array dimensions](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html)

In [12]:
import numpy as np

In [13]:
# To change or get the dimensions of an array, use the ndim attribute
a = np.array([1, 2, 3], ndmin=10)  # 10 dimensions
np.expand_dims(a, axis=0)  # add a dimension to the array
a = np.squeeze(a)  # remove single-dimensional entries from the shape of an array
print(a, a.ndim)


[1 2 3] 1


##### Scalar

In [14]:
scalar = np.array(42)
print(f'\n{scalar.ndim}-dim Scalar:\n{scalar}')


0-dim Scalar:
42


##### Vector

In [15]:
vector = np.array([1, 2, 3, 4, 5])
print(f'\n{vector.ndim}-dim Vector:\n{vector}')


1-dim Vector:
[1 2 3 4 5]


##### Matrix

In [16]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'\n{matrix.ndim}-dim Matrix:\n{matrix}')


2-dim Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Tensor

Most of the time, we will be working with tensors. A tensor is a generalization of vectors and matrices and is easily represented as an array. In fact, you can think of a matrix as a 2-dimensional array and a vector as a 1-dimensional array.

In [17]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(f'\n{tensor.ndim}-dim Tensor:\n{tensor}')


3-dim Tensor:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### [numpy array shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html)

The shape of an array is the number of elements in each dimension.

`np_array.shape` returns a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of dimensions, ndim.

In [18]:
x = np.arange(2, 11)
print(x, x.shape, x.ndim)
# To reshape an array it MUST HAVE the same number of elements as the original array
print('\n',x.reshape(3, 3))  # reshape() returns a new array with the specified shape   # 3 rows, 3 columns

[ 2  3  4  5  6  7  8  9 10] (9,) 1

 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [23]:
# Reshape 
print('Fortran order:\n', x.reshape(3, 3, order='F'))  # Fortran order
print('C order:\n', x.reshape(3, 3, order='C'))  # C order (default)
# Using 'A' will automatically choose the best order according to the array

Fortran order:
 [[ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]]
C order:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
