### Indexing & Slicing
Numpy offers several ways to index into arrays.

**Indexing**: Can be indexed with slices, but also with boolean or integer arrays (masks). This method is called `fancy indexing`. It creates copies not views.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

In [2]:
import numpy as np

To access the elements of an array, we can use the square brackets for slicing along each dimension, just as we did with Python lists. However, with arrays, we can provide a slice for each dimension of the array.

In [3]:
# Filtering array
arr = np.arange(0, 101, 10)
print(np.vectorize(lambda x: x**2 if x>0.5 else False)(arr))  # returns array with elements squared if >0.5, else returns element
print(arr[arr>50])  # returns array with elements >50
print(arr)

[False  True  True  True  True  True  True  True  True  True  True]
[ 60  70  80  90 100]
[  0  10  20  30  40  50  60  70  80  90 100]


### Multidimensional arrays

In [4]:
arr1 = np.random.randint(0, 100, (2, 10))
arr2 = np.random.randint(0, 100, (2, 10))
print(arr1)
print(arr2)

[[48 44 67  7  6 57 66 44 38 77]
 [79 64 30 62 31 89 80 47 53 91]]
[[16  6  9 45 89  8 68 27 43 39]
 [10 27 35 92 97 94 17 96 90 24]]


In [14]:
# ravel function returns flattened array. It can be used to flatten array in C or Fortran order
print(arr1.ravel(order='F'))  # returns flattened array in Fortran order
print(arr1.ravel(order='C'))  # returns flattened array in C order
print(arr1.ravel())  # returns flattened array (default order is C)

[48 79 44 64 67 30  7 62  6 31 57 89 66 80 44 47 38 53 77 91]
[48 44 67  7  6 57 66 44 38 77 79 64 30 62 31 89 80 47 53 91]
[48 44 67  7  6 57 66 44 38 77 79 64 30 62 31 89 80 47 53 91]


In [6]:
# Multi-dimensional array slicing & indexing
# arr[row, column]
print(f'first row: {arr1[0]}')  # first row
print(f'first column: {arr1[:, 0]}')  # first column
print(arr1[0, 0])  # first element

first row: [48 44 67  7  6 57 66 44 38 77]
first column: [48 79]
48


### Concatenation & Splitting

Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines `concatenate`, `stack` and `hstack`.

Using `split`, you can split an array into multiple sub-arrays as follows:  
`np.split(ary, indices_or_sections, axis=0)`
- `ary`: Array to be divided into sub-arrays.
- `indices_or_sections`: If `indices_or_sections` is an integer, N, the array will be divided into N equal arrays along `axis`. If such a split is not possible, an error is raised. If `indices_or_sections` is a 1-D array of sorted integers, the entries indicate where along `axis` the array is split. If an index exceeds the dimension of the array along `axis`, an empty sub-array is returned correspondingly.

In [7]:
print(np.stack((arr1, arr2), axis=1))  # concatenate arrays along axis=1 (column)
print('\n', np.hstack((arr1, arr2)))  # concatenate arrays horizontally
print('\n', np.vstack((arr1, arr2)))  # concatenate arrays vertically

[[[48 44 67  7  6 57 66 44 38 77]
  [16  6  9 45 89  8 68 27 43 39]]

 [[79 64 30 62 31 89 80 47 53 91]
  [10 27 35 92 97 94 17 96 90 24]]]

 [[48 44 67  7  6 57 66 44 38 77 16  6  9 45 89  8 68 27 43 39]
 [79 64 30 62 31 89 80 47 53 91 10 27 35 92 97 94 17 96 90 24]]

 [[48 44 67  7  6 57 66 44 38 77]
 [79 64 30 62 31 89 80 47 53 91]
 [16  6  9 45 89  8 68 27 43 39]
 [10 27 35 92 97 94 17 96 90 24]]


In [8]:
print(arr1, '\n')
print('\n', np.hsplit(arr1, 2))  # split array horizontally into 2 arrays
print('\n', np.vsplit(arr1, 2))  # split array vertically into 2 arrays

[[48 44 67  7  6 57 66 44 38 77]
 [79 64 30 62 31 89 80 47 53 91]] 


 [array([[48, 44, 67,  7,  6],
       [79, 64, 30, 62, 31]]), array([[57, 66, 44, 38, 77],
       [89, 80, 47, 53, 91]])]

 [array([[48, 44, 67,  7,  6, 57, 66, 44, 38, 77]]), array([[79, 64, 30, 62, 31, 89, 80, 47, 53, 91]])]
