# [Numpy](https://numpy.org/)
Is a python library for scientific computing. It provides a high-performance multidimensional array object, and tools for working with these arrays.
It's optimized for speed and memory usage. It's also the foundation of many other libraries, such as `pandas`, `scikit-learn`, and `matplotlib`...

In [1]:
import numpy as np
np.__version__

'1.24.1'

### Arrays
The main object in numpy is the `ndarray`. It's a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In numpy dimensions are called `axes`. The number of axes is `rank`.

In [2]:
np.array([1, 2, 3, 4, 5])  # 1D array
print(np.zeros((2)))  # 2x1 array of zeros
print(np.ones((2, 3)))  # 2x3 array of ones
print(np.full((2, 3), 7))  # 2x3 array of 7s
print(np.eye(3))  # 3x3 identity matrix

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
print(np.linspace(0, 100, 10))  # 10 numbers from 0 to 100 with equal step
print(np.arange(0, 100, 12.5))  # 10 numbers from 0 to 100 with step 12.5

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 0.  12.5 25.  37.5 50.  62.5 75.  87.5]


In [4]:
arr = np.random.random((2, 3))  # 2x3 array of random numbers
# arr = np.random.randn(10)  # 10 random numbers from NORMAL DISTRIBUTION
# arr = np.random.rand(10)  # 10 random numbers from UNIFORM DISTRIBUTION
# arr = np.random.binomial(10, 0.5, 10)  # 10 random numbers from BINOMIAL DISTRIBUTION
# arr = np.random.choice([1, 2, 3, 4, 5], size=(2, 3), replace=False)  # 2x3 array of random numbers from [1, 2, 3, 4, 5]
print(arr)

# Array Attributes
print(f'Shape: {arr.shape}')  # shape of array
print(f'Dimension: {arr.ndim}')  # number of dimensions
print(f'n Elements: {arr.size}')  # number of elements
print(f'dType: {arr.dtype}')  # data type of array

[[0.23399829 0.69250351 0.38408344]
 [0.52426399 0.58560604 0.77172601]]
Shape: (2, 3)
Dimension: 2
n Elements: 6
dType: float64


### Main Functions

In [5]:
# Copy
arr2 = arr.copy()  # Coping an array allows us to change the copy without changing the original array
arr2[:] = 0
print(arr)
print(arr2)

[[0.23399829 0.69250351 0.38408344]
 [0.52426399 0.58560604 0.77172601]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Sort
print(np.sort(arr, axis=0))  # sort along axis 0
print(f'.argsort():\n{arr.argsort()}')  # indices of sorted array

[[0.23399829 0.58560604 0.38408344]
 [0.52426399 0.69250351 0.77172601]]
.argsort():
[[0 2 1]
 [0 1 2]]


In [7]:
print(f'.max(): {arr.max():>24}')  # max value in array
print(f'.min(): {arr.min():>24}')  # min value in array
print(f'.sum(): {arr.sum():>24}')  # sum of all values in array
# ptp = peak to peak
print(f'.ptp(): {arr.ptp():>24}')  # difference between max and min values in array

# Array Indexing
print(f'.argmax(): {arr.argmax():>4}')  # index of max value in array
print(f'.argmin(): {arr.argmin():>4}')  # index of min value in array

.max():       0.7717260100505652
.min():       0.2339982938633669
.sum():       3.1921812932116493
.ptp():       0.5377277161871983
.argmax():    5
.argmin():    0


### Statistics

In [8]:
print(f'.mean():{arr.mean()}')  # mean value in array
print(f'.std(): {arr.std()}')  # standard deviation of array
print(f'.var(): {arr.var()}')  # variance of array
print(f'.median(): {np.median(arr)}')  # median of array

# Percentiles
print(f'.percentile(50): {np.percentile(arr, 50):>}')  # 50th percentile

.mean():0.5320302155352749
.std(): 0.18112965416664614
.var(): 0.032807951618528834
.median(): 0.5549350170903644
.percentile(50): 0.5549350170903644
