### [Numpy Operations](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [27]:
import numpy as np

arr1 = np.arange(9).reshape(3, 3)
arr2 = np.arange(9, 18).reshape(3, 3)
print(arr1)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


### Lineal Algebra

In [36]:
# Some linear algebra operations
print(arr1.T)  # Transpose
print(np.dot(arr1, arr2))  # Matrix multiplication
print(np.cross(arr1, arr2))  # Cross product

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[ 42  45  48]
 [150 162 174]
 [258 279 300]]
[[-9 18 -9]
 [-9 18 -9]
 [-9 18 -9]]


In [38]:
print(np.trace(arr1))  # Trace: sum of diagonal elements
print(np.linalg.det(arr1))  # Determinant
print(np.invert(arr1))  # Inverse

12
0.0
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


In [45]:
# Eigenvalues
print(np.linalg.eigvals(arr1))  # return eigenvalues & eigenvectors

[ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]


### System of Linear Equations

In [42]:
# solve a linear system
A = np.array([[1, 1, 1], [0, 2, 5], [2, 5, -1]])
b = np.array([6, -4, 27])

print('x: ', np.linalg.solve(A, b))

x:  [ 5.  3. -2.]
